apiVersion: v1
kind: Pod
metadata:
  name: nodeapp-pod
  labels:
    app: nodeapp-pod
spec:
  containers:
    - name: nodeapp
      image: trinh00thien/my-docker-app:tagVersion
      ports:
        - containerPort: 5000
