apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: trinh00thien/my-docker-app:tagVersion
      ports:
        - containerPort: 5000
